# Working with Pandas - Part 2

In [1]:
# Complete your imports
import pandas as pd
import numpy as np

In [2]:
s = pd.Series({'A': 15, 'B': 8, 'C': 6, 'D': 2, 'E': 10})  #Creating a pandas Series object
s

A    15
B     8
C     6
D     2
E    10
dtype: int64

####  The Series object `s` is initialized with data in the form of a Python dictionary. Each key-value pair in the dictionary represents a label-value pair in the Series. In this case, the keys are the labels ('A', 'B', 'C', 'D', and 'E'), and the corresponding values are the data associated with each label (15, 8, 6, 2, and 10, respectively).

### Structure of the Code:

The code has two lines:

- Line 1: Creates a pandas Series object named `s` with data provided in the form of a dictionary.
- Line 2: Displays the content of the Series `s`.

### How the Code Works:

1. The first line of code initializes a pandas Series object named `s` with data from a dictionary. The `pd.Series()` function is used to create the Series, and it takes the dictionary as an argument. The keys of the dictionary become the labels of the Series, and the values become the corresponding data associated with each label.

2. After the Series `s` is created, the second line of code simply prints the content of the Series, which displays the labels and their associated values.

### Notable Features/Functionality:

1. **Pandas Series**: The code demonstrates how to create a pandas Series object using the `pd.Series()` function. Series are useful for handling one-dimensional data and allow easy access and manipulation of data with labeled indexes.

2. **Data from Dictionary**: The data used to initialize the Series comes from a Python dictionary. This allows for convenient and structured representation of data where each label is associated with a value.

### Use Case:
Suppose you are analyzing the performance of different students in a class, and you have data on their scores in five different subjects (A, B, C, D, and E). Using pandas Series, you can store and manipulate this data efficiently. The labels 'A', 'B', 'C', 'D', and 'E' represent the subject names, and the corresponding values represent the scores of individual students. With the Series, you can perform various operations like calculating the average score, finding the maximum score, filtering data based on conditions, and plotting the scores for visualization.

In [3]:
df = pd.DataFrame({'age': s, 'test': {'A': 2.6, 'B': 69.27, 'C': 14.2, 'D': 8.0, 'G': 5.93}})  #Creating a dataframe
df

age   test
A  15.0   2.60
B   8.0  69.27
C   6.0  14.20
D   2.0   8.00
E  10.0    NaN
G   NaN   5.93


### Detailed Explanation:

1. The code snippet creates a pandas DataFrame, which is a two-dimensional tabular data structure in Python.

2. The DataFrame is initialized with two columns: 'age' and 'test'.

3. The 'age' column is assigned the values from an existing variable 's'. The assumption is that 's' is a pandas Series or any iterable containing the age values. For example, if 's' is a Series like [25, 30, 35, 40, 45], the 'age' column in the DataFrame will be populated with these age values.

4. The 'test' column is initialized with a dictionary of values. Each key-value pair in the dictionary represents a test label (e.g., 'A', 'B', 'C', 'D', 'E') and its corresponding value (e.g., 2.6, 69.27, 14.2, 8.0, 5.93). This means that each row in the 'test' column will have a different test label associated with it, and the values in the dictionary will be mapped accordingly. For example, the first row may have 'A' as the test label with a value of 2.6, the second row may have 'B' as the test label with a value of 69.27, and so on.

5. The resulting DataFrame is stored in the variable 'df'. The 'df' variable can now be used for further data analysis, manipulation, visualization, or any other data-related tasks.

### Notable Features/Functionality:

1. **DataFrame Creation:** The code demonstrates the creation of a pandas DataFrame using a dictionary for one column and an existing variable for another column.

2. **Column Assignment:** The DataFrame is created with two columns, 'age' and 'test', where the 'age' column is assigned values from an existing variable 's', and the 'test' column is initialized with a dictionary of values.

3. **Hierarchical Data:** The 'test' column uses a dictionary of values, allowing for hierarchical data representation within a DataFrame. This feature is useful when dealing with data that has multiple attributes or sub-properties associated with each row.



In [4]:
state_data = {'State':['Alabama','Alaska','Arizona','Arkansas'], 'PostCode':['AL','AK','AZ','AR'], 'Area':['52,423', '656,424','*','53,182'], 'Pop':['4,040,587', '550,043', '3,665,228','2,350,725']}
state_data



{'State': ['Alabama', 'Alaska', 'Arizona', 'Arkansas'],
 'PostCode': ['AL', 'AK', 'AZ', 'AR'],
 'Area': ['52,423', '656,424', '*', '53,182'],
 'Pop': ['4,040,587', '550,043', '3,665,228', '2,350,725']}

### Data Structure
The `state_data` dictionary is structured as follows:
- 'State': A list of strings representing the names of the states ('Alabama', 'Alaska', 'Arizona', 'Arkansas').
- 'PostCode': A list of strings containing the postal codes of the respective states ('AL', 'AK', 'AZ', 'AR').
- 'Area': A list of strings representing the land area of the states in square miles ('52,423', '656,424', '*', '53,182'). Note that one of the entries has an asterisk ('*') indicating missing or unknown data.
- 'Pop': A list of strings representing the population of each state ('4,040,587', '550,043', '3,665,228', '2,350,725').

### Functionality and Use Cases

1. **Data Analysis**: Researchers or analysts can use this data to perform statistical analyses, comparing the population and land area of different states.

2. **Data Visualization**: This data can be visualized using graphs, charts, or maps to present state-specific information in a visually appealing manner.

3. **Lookup by State Name**: One can retrieve information about a specific state by searching for its name in the 'State' list.

4. **Postal Code Lookup**: Given a postal code, one find the corresponding state by searching in the 'PostCode' list.

5. **Handling Missing Data**: The asterisk (*) in the 'Area' list indicates missing data, which require special handling in data processing and analysis.



In [5]:
#When we define the dataframe, we can use the columns argument to set the order of the columns. 
stdf = pd.DataFrame(state_data, columns=['State','PostCode','Area','Pop'])
stdf


State PostCode     Area        Pop
0   Alabama       AL   52,423  4,040,587
1    Alaska       AK  656,424    550,043
2   Arizona       AZ        *  3,665,228
3  Arkansas       AR   53,182  2,350,725

In [6]:
stdf['Area']   # gets the Area column
#stdf.Area	# also gets the Area column

0     52,423
1    656,424
2          *
3     53,182
Name: Area, dtype: object

In [7]:
stdf['Area'][0]   # gets the item at index 0, column ‘Area’


'52,423'

In [8]:
stdf[0:2]

State PostCode     Area        Pop
0  Alabama       AL   52,423  4,040,587
1   Alaska       AK  656,424    550,043


`[0:2]`: This is the slicing notation in Python. It is used to extract a portion of a collection (e.g., list, tuple, string) based on the specified indices. In this case, the slicing notation `[0:2]` indicates that we want to extract elements from index 0 (inclusive) to index 2 (exclusive) from the collection assigned to the variable `stdf`.

### How It Works:

Let's consider different data types to understand how the slicing works:

#### 1. List Example:

Suppose `stdf` is a list containing elements `[10, 20, 30, 40, 50]`. When we apply the slicing notation `[0:2]`, it will extract elements from index 0 to index 2, excluding the element at index 2. So the result will be a new list `[10, 20]`.

```python
stdf = [10, 20, 30, 40, 50]
result = stdf[0:2]
print(result)  # Output: [10, 20]
```

#### 2. String Example:

If `stdf` is a string containing characters `"Hello, World!"`, using the slicing notation `[0:2]` will extract characters from index 0 to index 2 (excluding the character at index 2). The result will be a new string `"He"`.

```python
stdf = "Hello, World!"
result = stdf[0:2]
print(result)  # Output: "He"
```


In [9]:
stdf[0:2]["Pop"]   #Getting complicated. Pandas offers better wasy to navigate dataframes - we will see them later

0    4,040,587
1      550,043
Name: Pop, dtype: object

In [10]:
#Next we redefine the index values to be the State column.

stdf2 = stdf.set_index('State')
stdf2


PostCode     Area        Pop
State                                
Alabama        AL   52,423  4,040,587
Alaska         AK  656,424    550,043
Arizona        AZ        *  3,665,228
Arkansas       AR   53,182  2,350,725


The code snippet that uses the Pandas library to redefine the index values of a DataFrame called `stdf` and stores the result in a new DataFrame called `stdf2`.


### How it Works:
1. In real-world scenarios, it is often more useful to have meaningful and unique indices based on the data itself. In this case, it appears that the DataFrame `stdf` contains data related to different states.

2. We use the `set_index()` method to redefine the index values of the `stdf` DataFrame. It takes a single argument, `'State'`, which specifies the column to be used as the new index. By setting the index to the `'State'` column, the values in this column will become the new row indices for the DataFrame.

3. The resulting DataFrame is stored in a new variable called `stdf2`. This means that `stdf2` will have the same data as `stdf`, but the rows will be indexed by the values from the `'State'` column.


### Use Cases:
1. By redefining the index to be the `'State'` column, the DataFrame becomes more convenient to work with. Accessing rows by state names is now much simpler and more intuitive. For example, `stdf2.loc['Texas']` would give the data for Texas directly.

2. The redefined index supports more efficient data aggregation, filtering, and grouping based on states.

3. This approach is especially useful when performing time-series analysis or working with any dataset that has meaningful and unique identifiers associated with each row.



## Slicing - using loc and iloc

The loc[ ] property is used to slice a pandas DataFrame or Series and access row(s) and column(s) **by label**

In [11]:
stdf2.loc[:,"Area":"Pop"]

Area        Pop
State                       
Alabama    52,423  4,040,587
Alaska    656,424    550,043
Arizona         *  3,665,228
Arkansas   53,182  2,350,725

**Description:**

1. `stdf2`: This is the DataFrame from which we want to extract a subset of data. It's assumed that `stdf2` has already been defined and contains multiple rows and columns.

2. `.loc[]`: The `.loc` accessor is used to access rows and columns by label. In this case, it is used to specify the rows and columns we want to extract.

3. `[:, "Area":"Pop"]`: The first part (`:`) before the comma indicates that we want to select all rows. The second part (`"Area":"Pop"`) after the comma specifies the range of columns we want to select, from "Area" to "Pop" (inclusive).

**How it works:**

When this line of code is executed, pandas will extract a subset of data from the `stdf2` DataFrame, containing all rows and only the columns that fall within the range "Area" to "Pop" (both inclusive).

**Notable Features / Functionality:**

1. Data Extraction: The code allows you to extract a subset of data from a DataFrame based on the specified range of columns. It's a convenient way to work with specific sets of data.

2. Label-Based Selection: The `.loc` accessor is used for label-based selection, which means you can specify columns by their labels (column names) rather than their positional indices.



In [12]:
stdf.loc[:,"Area":"Pop"]   #The non-indexed version result is different

Area        Pop
0   52,423  4,040,587
1  656,424    550,043
2        *  3,665,228
3   53,182  2,350,725

In [13]:
stdf2.loc["Alaska":"Arkansas","Area":"Pop"]  #It will include the whole range of items you specify

Area        Pop
State                       
Alaska    656,424    550,043
Arizona         *  3,665,228
Arkansas   53,182  2,350,725

In [14]:
stdf2 # note the dataset remains intact

PostCode     Area        Pop
State                                
Alabama        AL   52,423  4,040,587
Alaska         AK  656,424    550,043
Arizona        AZ        *  3,665,228
Arkansas       AR   53,182  2,350,725

In [15]:
stdf2.iloc[1]  #Row 1 (counting from zero ) = row 2 counting from 1 = The row with the data for Alaska

PostCode         AK
Area        656,424
Pop         550,043
Name: Alaska, dtype: object


## Code Explanation: Slicing


1. The DataFrame: 
   The code assumes that there is a DataFrame named `stdf2` containing tabular data.

2. DataFrame Indexing:
   DataFrames are indexed, meaning each row has a unique label (index) associated with it. Indexing in Pandas allows us to access specific rows or columns.

3. Code Line Explanation:
   Let's break down the code line step by step:

   ```python
   stdf2.iloc[1]
   ```

   - `stdf2`: This is the DataFrame from which we want to extract data.
   - `.iloc`: This is a property of the DataFrame that stands for "integer-location-based indexing." It allows us to access rows or columns using integer-based positions rather than the default label-based indexing.
   - `[1]`: This is the index value specified within square brackets. Here, `[1]` represents the integer position 1, which corresponds to the second row in the DataFrame (remember 0-based indexing, so the second row has index 1).

4. Data Retrieval:
   The code line, `stdf2.iloc[1]`, retrieves the second row from the DataFrame `stdf2`. The result is a Pandas Series, which is a one-dimensional labeled array.
   
5. The Resulting Data:
   The extracted row (the second row) represents the data for the state of Alaska, as indicated by the comment at the end of the code line.



In [16]:
stdf2.iloc[1:4,1:3]  #same as previous loc[] statement

Area        Pop
State                       
Alaska    656,424    550,043
Arizona         *  3,665,228
Arkansas   53,182  2,350,725

`subset = stdf2.iloc[1:4, 1:3]`:  extracts a subset of data from the DataFrame `stdf2` using the `.iloc` attribute. 

   - The first argument `1:4` indicates that we want to select **rows** with integer positions from index 1 to index 3 (since the end index is exclusive). So, we are extracting the rows at positions 1, 2, and 3 (indexing starts from 0).

   - The second argument `1:3` indicates that we want to select **columns** with integer positions from index 1 to index 2 (end index is exclusive). Thus, we are extracting columns at positions 1 and 2.

   - The result of this slicing operation is stored in the variable `subset`, which will be a new pandas DataFrame containing the selected rows and columns.

### Notable Features/Functionality
- The code uses pandas DataFrame `.iloc` for integer-location based indexing to select specific rows and columns.
- The slicing operation allows you to extract a subset of data from the original DataFrame without modifying the original data.
- The code extracts rows with index positions 1, 2, and 3 and columns with index positions 1 and 2 from the original DataFrame, creating a new DataFrame `subset` containing only the selected data. This allows you to work with a smaller, specific portion of your data for further analysis or manipulation.

## Cleaning and understanding a dataset

In [17]:
stdf

State PostCode     Area        Pop
0   Alabama       AL   52,423  4,040,587
1    Alaska       AK  656,424    550,043
2   Arizona       AZ        *  3,665,228
3  Arkansas       AR   53,182  2,350,725

In [18]:
#Replacing '*' with '0'

stdf = stdf.replace('*','0')
stdf


State PostCode     Area        Pop
0   Alabama       AL   52,423  4,040,587
1    Alaska       AK  656,424    550,043
2   Arizona       AZ        0  3,665,228
3  Arkansas       AR   53,182  2,350,725

### Code Explanation:

The purpose of this code is to replace all occurrences of the character `*` in the variable `stdf` with the character `0`. The modified string is then stored back in the same variable `stdf`. 

Line 2: `stdf = stdf.replace('*', '0')`: Replaces all occurrences of the character `*` with the character `0` in the string stored in the variable `stdf`. Here, `stdf` is assumed to be a string variable. The `replace()` method is a built-in method for strings in Python that allows you to replace substrings within a string.


### Functionality and Use Cases:

- This method allows you to replace one substring with another within a string, and it is case-sensitive.
- It performs a simple character substitution, which can be useful in various scenarios, such as cleaning up data or standardizing input.
- Since Python strings are immutable, the `replace()` method returns a new modified string, and that's why the result is assigned back to the same variable `stdf`.
- If `stdf` is not a string, this code may raise an AttributeError, indicating that the `replace()` method is not available for the data type being used.





### We want to remove the commas "," in the values

In [19]:
# Get information on the structure and data types in the data frame - Very useful
stdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   State     4 non-null      object
 1   PostCode  4 non-null      object
 2   Area      4 non-null      object
 3   Pop       4 non-null      object
dtypes: object(4)
memory usage: 256.0+ bytes


In [20]:
mean_pop = stdf['Pop'].mean()  # Let's get the average population value

TypeError: Could not convert 4,040,587550,0433,665,2282,350,725 to numeric

There are issues with the data type for some of the columns. Let's try to fix them

In [ ]:
stdf['Area'] = stdf['Area'].astype(int)
stdf

#### The commas are getting in the way

We will use the map() function to start cleaning the dataset. See: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.map.html

In [ ]:
def item_replace(xstr):
   return xstr.replace(',','')        # in a string, replace any occurrence of ‘,’ with empty string

stdf['Pop'] = stdf['Pop'].map(item_replace)
stdf



### Code Explanation:

1. The code defines a function called `item_replace(xstr)`. The purpose of this function is to take a string as input (`xstr`) and return the string with all occurrences of a comma (`,`) removed.

2. `xstr.replace(',', '')`: This line of code utilizes the `replace()` method available for strings in Python. It replaces all occurrences of the comma (`,`) character with an empty string (`''`). 

3. `stdf['Pop']`: DataFrame called `stdf`, and accesses a specific column named `'Pop'`.

4. `.map(item_replace)`: The `map()` method in this context is being used to apply the `item_replace` function to each element of the `'Pop'` column. It iterates over each value in the column, passes it to the `item_replace` function, and replaces the value in the column with the result of the function.

5. DataFrame `stdf` is being modified in place by the `.map()` operation.

### Functionality:

This code processes a specific column (`'Pop'`) in the DataFrame `stdf` and remove any commas from its elements. It does so by defining a function `item_replace` that replaces commas with an empty string and then applying this function to all elements in the `'Pop'` column using the `.map()` method.

### Example:

Let's consider an example DataFrame `stdf` with a 'Pop' column containing population numbers:

```
stdf:
   Country         Pop
0  USA             328,200,000
1  China           1,398,300,000
2  India           1,366,400,000
3  Brazil          211,000,000
4  Russia          145,900,000
```

After applying the provided code, the `'Pop'` column will be modified as follows:

```
stdf:
   Country         Pop
0  USA             328200000
1  China           1398300000
2  India           1366400000
3  Brazil          211000000
4  Russia          145900000
```

All the commas have been removed from the `'Pop'` column, and the numbers are now represented as integers without any formatting. This can be helpful for further numerical analysis or calculations that may require the population data in a numeric format.

### Use Case:

The code can be particularly useful when working with datasets that contain numeric values in string format, such as financial data with currency symbols or large numbers with commas as thousands separators. By removing unwanted characters like commas, you can convert the strings into numerical data, enabling more straightforward computations and analysis.

In [ ]:
stdf['Area'] = stdf['Area'].map(item_replace) # remove commas from area
stdf


In [ ]:
stdf[['Area','Pop']] = stdf[['Area','Pop']].astype(int)   #Try again to convert to integer
stdf

In [ ]:
stdf.dtypes   #Verify

In [ ]:
stdf.info()

In [ ]:
mean_pop = stdf['Pop'].mean()  # Try again to get the average population value
mean_pop

In [ ]:
mean_area = stdf['Area'].mean()
mean_area

We will use the mask method to replace the 0 area value with the mean area value. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mask.html

In [ ]:
stdf['Area']=stdf.Area.mask(stdf.Area == 0, mean_area) # Assigns the mean to any zero values
stdf


### Code Explanation:



1. **`stdf['Area']=stdf.Area.mask(stdf.Area == 0, mean_area)`**:

   A combination of two Pandas functions, `mask()` and `==` (equality operator). Let's break it down:

   - `stdf['Area']`: This syntax accesses the column 'Area' within the DataFrame `stdf`.

   - `stdf.Area == 0`: This part creates a boolean mask (a boolean array) by checking if each value in the 'Area' column is equal to 0. The result is a boolean Series where each element is `True` if the corresponding 'Area' value is 0, otherwise `False`.

   - `mask(condition, mean_area)`: The `mask()` function is used to replace values in the DataFrame based on a given condition. In this case, the `condition` is `stdf.Area == 0` (the boolean mask), and `mean_area` is another variable that likely holds the mean value of the 'Area' column.

   - `mean_area`: This variable is used as a replacement value for the cells where the condition `stdf.Area == 0` is `True`. It seems like the intention is to fill the cells with 0 values with the mean value of the 'Area' column.

   So, the purpose of this line is to replace all the occurrences of 0 in the 'Area' column of the DataFrame `stdf` with the mean value stored in the `mean_area` variable.

2. **`stdf`**:

   After performing the above operation, the DataFrame `stdf` is returned, with the updated 'Area' column.

### Example and Use Case:

To better understand the code's functionality, let's consider another example:

Suppose we have the following DataFrame `stdf`:

```
   ID  Area
0   1   200
1   2   300
2   3     0
3   4   150
4   5     0
5   6   400
```

Here, there are two zero values in the 'Area' column at index 2 and 4. Let's assume the mean_area variable holds the mean value of the 'Area' column, which is 250.

Now, when we execute the provided code:

```python
stdf['Area']=stdf.Area.mask(stdf.Area == 0, mean_area)
```

The DataFrame `stdf` will be updated as follows:

```
   ID  Area
0   1   200
1   2   300
2   3   250
3   4   150
4   5   250
5   6   400
```

The zero values in the 'Area' column have been replaced with the mean value, which is 250 in this case.

### Functionality:

- The `mask()` function from Pandas, which is a powerful tool for conditional data manipulation.

- The code handles missing or zero values in the 'Area' column by replacing them with the mean value.

- Useful in data preprocessing tasks where filling missing or invalid values with meaningful statistics (like the mean) can improve the quality of the dataset for analysis or modeling purposes.

- It's important to note that using the mean to replace missing or zero values is just one approach. Depending on the context and nature of the data, other imputation strategies, such as median or forward/backward fill, may be more appropriate.

## Handling NAN values

In [22]:
d1 = {'A' : ['Alpha','Beta','Gamma', 'Delta'], 'B' : [11., 3., np.nan, 1.]}
df1 = pd.DataFrame(d1)
df1


A     B
0  Alpha  11.0
1   Beta   3.0
2  Gamma   NaN
3  Delta   1.0

Let's break down the code step by step:

```python
# Step 1: Create a dictionary 'd1' with two keys 'A' and 'B'
d1 = {'A': ['Alpha', 'Beta', 'Gamma', 'Delta'], 'B': [11., 3., np.nan, 1.]}
```

In this step, we create a dictionary 'd1' with two key-value pairs. The key 'A' maps to a list of strings ['Alpha', 'Beta', 'Gamma', 'Delta'], and the key 'B' maps to a list of floating-point numbers [11.0, 3.0, np.nan, 1.0]. The 'np.nan' represents a special floating-point value 'Not a Number', which is often used to denote missing or invalid data.

```python
# Step 2: Convert the dictionary 'd1' into a DataFrame 'df1'
df1 = pd.DataFrame(d1)
```

In this step convert the dictionary 'd1' into a DataFrame named 'df1'. The keys of the dictionary ('A' and 'B') will become the column labels, and the corresponding lists will become the data in those columns. The resulting DataFrame looks like this:

```
        A     B
0   Alpha  11.0
1    Beta   3.0
2   Gamma   NaN
3   Delta   1.0
```

The value 'np.nan' in the 'B' column represents missing data. Pandas provides built-in methods to handle missing data, such as dropping rows or filling missing values with some default value.

By default, Pandas will infer the data types of columns in the DataFrame. In this case, 'A' will be inferred as a string (object) data type, and 'B' will be inferred as a float64 data type.

Now, let's review

Example 1: Accessing Data

You can access specific columns or rows of the DataFrame using indexing and slicing. For instance, to access the 'A' column, you can use:

```python
column_A = df1['A']
print(column_A)
# Output: 
# 0    Alpha
# 1     Beta
# 2    Gamma
# 3    Delta
# Name: A, dtype: object
```

Example 2: Filtering Data

You can filter the DataFrame based on specific conditions. For example, let's filter rows where the value in column 'B' is greater than 3:

```python
filtered_df = df1[df1['B'] > 3]
print(filtered_df)
# Output:
#       A     B
# 0  Alpha  11.0
```

Example 3: Handling Missing Data

You can check for missing data and handle it accordingly. For instance, to drop rows containing NaN values:

```python
cleaned_df = df1.dropna()
print(cleaned_df)
# Output:
#        A    B
# 0  Alpha 11.0
# 1   Beta  3.0
# 3  Delta  1.0
```


In [23]:
mean_B = df1['B'].mean(skipna=True)
mean_B


5.0



## Description:
Calculates the mean of the values in column 'B' of a DataFrame named 'df1'. The mean is computed by excluding any missing or NaN (Not a Number) values in column 'B'.

## Structure:
`mean_B = df1['B'].mean(skipna=True)`: This line of code calculates the mean of column 'B' in the DataFrame 'df1' and assigns the result to the variable 'mean_B'.
   - `df1['B']`: Accesses the 'B' column of the DataFrame 'df1'.
   - `.mean(skipna=True)`: Calls the 'mean()' method on the 'B' column to calculate the mean, and 'skipna=True' argument ensures that any missing or NaN values are excluded from the calculation.



## How it works:
The code uses Pandas, a powerful Python library for data manipulation and analysis. The DataFrame 'df1' should be loaded or created before executing this code, and it should contain a column named 'B' from which the mean needs to be calculated.

1. The line `mean_B = df1['B'].mean(skipna=True)` starts by accessing column 'B' of 'df1' using `df1['B']`. The 'mean()' method is then called on this column, which calculates the mean of all the values in that column.

2. The `skipna=True` argument ensures that any missing or NaN values in column 'B' are skipped during the mean calculation. If there are NaN values and `skipna` is set to False, the result would be NaN. By setting it to True, any missing values are ignored, and the mean is computed only from valid numerical data.




In [24]:
mean_B = df1['B'].mean()  # same result. #skipna was there by default 
mean_B


5.0

In [25]:
df1['B'] = df1['B'].mask(df1['B'].isnull(), mean_B)
df1


A     B
0  Alpha  11.0
1   Beta   3.0
2  Gamma   5.0
3  Delta   1.0



### Code Explanation: Similar as above shown in the area example

1. `df1['B']`: This part of the code accesses the column labeled 'B' in the DataFrame `df1`. 

2. `.mask(condition, replacement)`: The `.mask()` method is a pandas DataFrame function that allows you to replace values based on a given condition. In this case, it is used to replace specific values in the column 'B'.

3. `df1['B'].isnull()`: This part of the code creates a boolean mask for the column 'B'. A boolean mask is a True/False array that indicates whether each element in the column is null (NaN) or not.

4. `mean_B`: It seems like `mean_B` is a variable that holds the mean value to be used for replacing the null values in column 'B'.

5. `df1['B'].mask(df1['B'].isnull(), mean_B)`: This part of the code applies the mask created in step 3 to the column 'B' and replaces all null values (where the mask is True) with the value stored in the variable `mean_B`.

6. `df1['B'] = df1['B'].mask(df1['B'].isnull(), mean_B)`: The modified column with the replaced values is assigned back to the column 'B' in `df1`, effectively updating the DataFrame with the changes made.




## Deleting rows or columns

In [26]:
df1

A     B
0  Alpha  11.0
1   Beta   3.0
2  Gamma   5.0
3  Delta   1.0

In [ ]:
df1.drop(2)    #takes out entry 2 but does not delete it from the dataframe


### Code Structure and Functionality
The code consists of a single line of Python code. The structure of the line is as follows:

1. `df1`: This represents the DataFrame object to which the `drop()` method is being applied.
2. `.drop(2)`: This is the method call. The `drop()` method is used to remove a row from the DataFrame. The parameter `2` indicates the index label of the row that should be removed.

### How It Works
The `drop()` method in Pandas is used to remove rows or columns from a DataFrame. When applied to a DataFrame, **it returns a new DataFrame with the specified rows or columns removed. However, the original DataFrame remains unaffected.**

In this specific case, the method `drop(2)` is called on the DataFrame `df1`. This means the row with the index label "2" will be taken out of the DataFrame `df1`, and the resulting DataFrame with this row removed will be returned. The original DataFrame `df1` remains unchanged.

### Notable Features and Functionality
1. **Non-destructive Operation**: The `drop()` method, as used in this code, performs a non-destructive operation. It doesn't modify the original DataFrame `df1`, ensuring data integrity and avoiding accidental data loss.





In [27]:
df1

A     B
0  Alpha  11.0
1   Beta   3.0
2  Gamma   5.0
3  Delta   1.0

In [33]:
df1

A     B
0  Alpha  11.0
1   Beta   3.0
3  Delta   1.0

In [35]:
df1.drop(2, inplace=True) # note the error 

KeyError: '[2] not found in axis'

After running this code, the DataFrame `df1` will no longer include the row with index `2`, effectively removing the information from the DataFrame. Note that the original DataFrame `df1` will be modified directly since we used `inplace=True`.

#### Dropping a column

In [37]:
df1.drop('A', axis=1,)

B
0  11.0
1   3.0
3   1.0


### Structure

1. `df1`: This is the DataFrame object on which the `drop()` method is being called.

2. `.drop()`: This is the method used to drop/remove columns from the DataFrame.

3. `'A'`: This is the parameter passed to the `drop()` method, specifying the column to be dropped. Here, the column with the label `'A'` will be removed from `df1`.

4. `axis=1`: This is another parameter passed to the `drop()` method, indicating that we want to drop a column and not a row. In pandas, `axis=0` represents rows, and `axis=1` represents columns.

### Functionality

The code will remove the column labeled `'A'` from the DataFrame `df1`. It will modify `df1` in-place and update it to have all columns except column `'A'`.



In [40]:
df1.drop('A', axis=1, inplace = True)

KeyError: "['A'] not found in axis"